### ISSUE TITLE
Bump to Scala 2.12.0

### ISSUE THREAD

**Issue by 3tty0n** [scala-js/scala-js-dom#247]
Scala 2.12.0 is now available. 

http://www.scala-lang.org/news/2.12.0

**Comment by sjrd** [comment]
Note that we've already published scalajs-dom 0.9.1 for Scala 2.12.

**Comment by jrudolph** [comment]
The documentation page seems to be out of date, though. It still shows 0.9.0 as latest version.

**Comment by exoego** [comment]
I think this issue can be closed, since it is already addressed.


```
libraryDependencies += "org.scala-js" %%% "scalajs-dom" % "0.9.7"

then enjoy the types available in org.scalajs.dom. scalajs-dom 0.9.7 is built and published for Scala.js 0.6.17 and later, Scala.js 1.0.0-M7, with Scala 2.10, 2.11, 2.12, 2.13.0-RC1. It will also most likely be published as is for further versions of Scala.js 1.x and 2.13.x in the future. 
```
in http://scala-js.github.io/scala-js-dom/
